'use client';

import React, { useState, useMemo } from 'react';
import { DashboardLayout } from '@/components/layout/DashboardLayout';
import { StaffStatementFilter } from '@/components/staff/StaffStatementFilter';
import { StaffStatementSummary } from '@/components/staff/StaffStatementSummary';
import { StaffStatementTable } from '@/components/staff/StaffStatementTable';
import { Button } from '@/components/ui/button';
import { History, Printer, Download, User } from 'lucide-react';
import { mockStaff, mockStaffStatements } from '@/data/mock-data';
import { formatCurrency } from '@/lib/utils';

export default function StaffStatementPage() {
  const [selectedStaffId, setSelectedStaffId] = useState('');
  const [dateRange, setDateRange] = useState({
    start: '2026-01-01',
    end: '2026-12-31'
  });

  const selectedStaff = useMemo(() => {
    return mockStaff.find(s => s.id === selectedStaffId) || null;
  }, [selectedStaffId]);

  const filteredEntries = useMemo(() => {
    if (!selectedStaffId) return [];
    
    return mockStaffStatements.filter(entry => {
      const matchesStaff = entry.staffId === selectedStaffId;
      const matchesDate = entry.date >= dateRange.start && entry.date <= dateRange.end;
      return matchesStaff && matchesDate;
    }).sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());
  }, [selectedStaffId, dateRange]);

  const handlePrint = () => {
    window.print();
  };

  return (
    <DashboardLayout>
      <div className="space-y-6 print:p-0">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 print:hidden">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 bg-orange-100 rounded-xl flex items-center justify-center text-orange-600">
              <History className="w-6 h-6" />
            </div>
            <div>
              <h1 className="text-3xl font-bold font-display tracking-tight">Staff Statement</h1>
              <p className="text-gray-500 mt-1">View salary history, advance payments, and deductions for employees.</p>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <Button variant="outline" className="gap-2" onClick={handlePrint} disabled={!selectedStaffId}>
              <Printer className="w-4 h-4" /> Print Statement
            </Button>
            <Button variant="outline" className="gap-2" disabled={!selectedStaffId}>
              <Download className="w-4 h-4" /> Export PDF
            </Button>
          </div>
        </div>

        {/* Print Header (Visible only when printing) */}
        <div className="hidden print:block border-b-2 border-gray-900 pb-6 mb-8">
          <div className="flex justify-between items-start">
            <div>
              <h1 className="text-4xl font-black tracking-tighter text-gray-900">ARANYA <span className="text-orange-500">FURNITURE</span></h1>
              <p className="text-sm font-bold text-gray-500 mt-1">STAFF SALARY STATEMENT</p>
            </div>
            <div className="text-right">
              <p className="text-sm font-bold text-gray-900">Date: {new Date().toLocaleDateString()}</p>
              <p className="text-xs text-gray-500">Generated by ERP System</p>
            </div>
          </div>
          
          {selectedStaff && (
            <div className="mt-8 grid grid-cols-2 gap-8">
              <div className="space-y-1">
                <p className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">Employee Details</p>
                <h2 className="text-xl font-black text-gray-900">{selectedStaff.name}</h2>
                <p className="text-sm font-bold text-orange-600">{selectedStaff.designation}</p>
                <p className="text-xs text-gray-500">{selectedStaff.department} Department</p>
              </div>
              <div className="text-right space-y-1">
                <p className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">Statement Period</p>
                <p className="text-sm font-bold text-gray-900">{dateRange.start} to {dateRange.end}</p>
                <p className="text-xs text-gray-500">Monthly Salary: {formatCurrency(selectedStaff.salary)}</p>
              </div>
            </div>
          )}
        </div>

        <div className="print:hidden">
          <StaffStatementFilter 
            selectedStaffId={selectedStaffId}
            onStaffChange={setSelectedStaffId}
            dateRange={dateRange}
            onDateChange={setDateRange}
          />
        </div>

        {selectedStaffId ? (
          <div className="space-y-6">
            <StaffStatementSummary entries={filteredEntries} />
            
            <div className="flex items-center justify-between">
              <h3 className="text-lg font-bold text-gray-900 flex items-center gap-2">
                <User className="w-5 h-5 text-orange-500" /> 
                Ledger for {selectedStaff?.name}
              </h3>
              <p className="text-sm text-gray-500">
                Showing {filteredEntries.length} entries
              </p>
            </div>

            <StaffStatementTable entries={filteredEntries} />
          </div>
        ) : (
          <Card className="p-20 border-none shadow-sm flex flex-col items-center justify-center text-center bg-white">
            <div className="w-20 h-20 bg-orange-50 rounded-full flex items-center justify-center text-orange-200 mb-6">
              <User className="w-10 h-10" />
            </div>
            <h2 className="text-2xl font-black text-gray-900">Select a Staff Member</h2>
            <p className="text-gray-500 max-w-sm mx-auto mt-2">
              Please choose an employee from the dropdown above to view their detailed salary statement and transaction history.
            </p>
          </Card>
        )}
      </div>
    </DashboardLayout>
  );
}

// Helper Card for the placeholder
function Card({ children, className }: { children: React.ReactNode, className?: string }) {
  return <div className={`rounded-xl border border-gray-200 ${className}`}>{children}</div>;
}
